# Generated by Django 5.2.4 on 2026-02-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(help_text='The original text entered by the user')),
                ('processed_text', models.TextField(help_text='The text after processing')),
                ('selected_options', models.CharField(help_text='Comma-separated list of operations applied', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Text Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
