# Generated by Django 5.2.4 on 2026-02-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypingTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('duration', models.IntegerField(help_text='Test duration in seconds')),
                ('wpm', models.FloatField(help_text='Words per minute')),
                ('accuracy', models.FloatField(help_text='Accuracy percentage')),
                ('total_chars', models.IntegerField(default=0, help_text='Total characters typed')),
                ('correct_chars', models.IntegerField(default=0, help_text='Correctly typed characters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Typing Test Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
